name: Merge Develop to Main on Release

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check last commit message
        id: check_commit
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          echo "Last commit: $LAST_COMMIT"
          if [[ "$LAST_COMMIT" == "chore(release)"* ]]; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge develop → main
        if: steps.check_commit.outputs.trigger == 'true'
        run: |
          git config user.name "AutoMerge Bot"
          git config user.email "bot@repo.local"
          git fetch origin main
          git checkout main
          git merge --no-ff develop -m "Merge develop → main [auto release]"
          git push origin main

  run-codacy:
    name: Run Codacy workflow
    needs: merge-to-main
    if: needs.merge-to-main.result == 'success'
    uses: ./.github/workflows/codacy.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  run-release-workflow:
    name: Run release generator
    needs: merge-to-main
    if: needs.merge-to-main.result == 'success'
    uses: ./.github/workflows/release.yml

  run-render-deploy:
    name: Deploy on render
    needs: merge-to-main
    if: needs.merge-to-main.result == 'success'
    uses: ./.github/workflows/render.yml
    secrets:
      MARIADB_HOSTNAME: ${{ secrets.MARIADB_HOSTNAME }}
      MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
      MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
      MARIADB_USER: ${{ secrets.MARIADB_USER }}
      MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
      deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

